/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as LabReportsRouteImport } from './routes/lab-reports'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AppointmentsRouteImport } from './routes/appointments'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const LabReportsRoute = LabReportsRouteImport.update({
  id: '/lab-reports',
  path: '/lab-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/appointments': typeof AppointmentsRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/inventory': typeof InventoryRoute
  '/lab-reports': typeof LabReportsRoute
  '/patients': typeof PatientsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/appointments': typeof AppointmentsRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/inventory': typeof InventoryRoute
  '/lab-reports': typeof LabReportsRoute
  '/patients': typeof PatientsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/appointments': typeof AppointmentsRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/inventory': typeof InventoryRoute
  '/lab-reports': typeof LabReportsRoute
  '/patients': typeof PatientsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/appointments'
    | '/billing'
    | '/dashboard'
    | '/inventory'
    | '/lab-reports'
    | '/patients'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/appointments'
    | '/billing'
    | '/dashboard'
    | '/inventory'
    | '/lab-reports'
    | '/patients'
    | '/settings'
  id:
    | '__root__'
    | '/appointments'
    | '/billing'
    | '/dashboard'
    | '/inventory'
    | '/lab-reports'
    | '/patients'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppointmentsRoute: typeof AppointmentsRoute
  BillingRoute: typeof BillingRoute
  DashboardRoute: typeof DashboardRoute
  InventoryRoute: typeof InventoryRoute
  LabReportsRoute: typeof LabReportsRoute
  PatientsRoute: typeof PatientsRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab-reports': {
      id: '/lab-reports'
      path: '/lab-reports'
      fullPath: '/lab-reports'
      preLoaderRoute: typeof LabReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AppointmentsRoute: AppointmentsRoute,
  BillingRoute: BillingRoute,
  DashboardRoute: DashboardRoute,
  InventoryRoute: InventoryRoute,
  LabReportsRoute: LabReportsRoute,
  PatientsRoute: PatientsRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
